### ISSUE TITLE
Annovar exiting with non-zero status

### ISSUE THREAD

**Issue by pifinski** [koelling/amplimap#7]
Hello,
I was trying to complete the variants_umi rule but always get an error mesage which causes amplimap to exit the analysis.
Error:

> Error in rule annotate_variants:
    jobid: 0
    output: analysis/variants_umi/SAMPLE1.vcf.normalized.vcf.gz.hg19_multianno.csv, analysis/variants_umi/SAMPLE1_S16.for_annovar.bed
>RuleException:
CalledProcessError in line 1581 of /mnt/tools/miniconda/envs/amplimap/lib/python3.6/site-packages/amplimap/Snakefile:
Command 'set -euo pipefail;  convert2annovar.pl analysis/variants_umi/SAMPLE1_S16.vcf.normalized.vcf.gz -format vcf4old --includeinfo > analysis/variants_umi/SAMPLE1_S16.for_annovar.bed;
>table_annovar.pl analysis/variants_umi/SAMPLE1_S16.for_annovar.bed "/share/user/Reference_Genomes/annovar/humandb" --buildver "hg19" --otherinfo -csvout -remove -protocol 'refGene,esp6500siv2_all,1000g2014oct_all,avsnp147,cosmic94_coding, cosmic94_noncoding,dbnsfp33a,clinvar_20150629,dbscsnv11,exac03,gnomad_genome,gnomad_exome' -operation g,f,f,f,f,f,f,f,f,f,f,f                     --outfile analysis/variants_umi/SAMPLE1_S16.vcf.normalized.vcf.gz ;' returned non-zero exit status 2.
  File "/mnt/tools/miniconda/envs/amplimap/lib/python3.6/site-packages/amplimap/Snakefile", line 1581, in __rule_annotate_variants
  File "/mnt/tools/miniconda/envs/amplimap/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Exiting because a job execution failed. Look above for error message

if I call the table_annovar.pl command with the given options it does run without an error and puts out an csv file.

I'm using Amplimap version 0.4.20
and annovar 2019Oct24

Has anybody had this behaviour before?
Thanks in advance!

**Comment by koelling** [comment]
You should be able to find a more descriptive error message in one of the log files. Have you had a look for that?

My best guess would be that there is an issue with one of the annovar databases. Are you sure they all exist?
