### ISSUE TITLE
fastq files from tutorials not accessible

### ISSUE THREAD

**Issue by jaanckae** [koelling/amplimap#8]
Trying to download the fastq files from the tutorials (in order to check installation), but getting an error.

`$ wget http://userweb.molbiol.ox.ac.uk/public/koelling/amplimap/tutorial_data/TLK2.tar`

`--2022-04-19 14:21:08--  http://userweb.molbiol.ox.ac.uk/public/koelling/amplimap/tutorial_data/TLK2.tar
Resolving userweb.molbiol.ox.ac.uk (userweb.molbiol.ox.ac.uk)... 163.1.16.66
Connecting to userweb.molbiol.ox.ac.uk (userweb.molbiol.ox.ac.uk)|163.1.16.66|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://userweb.molbiol.ox.ac.uk/public/koelling/amplimap/tutorial_data/TLK2.tar [following]
--2022-04-19 14:21:09--  https://userweb.molbiol.ox.ac.uk/public/koelling/amplimap/tutorial_data/TLK2.tar
Connecting to userweb.molbiol.ox.ac.uk (userweb.molbiol.ox.ac.uk)|163.1.16.66|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-04-19 14:21:10 ERROR 404: Not Found.`

Any other locations to download this data?

Thanks in advance

**Comment by koelling** [comment]
Thank you for pointing this out, I am looking into it.

**Comment by koelling** [comment]
Apologies for the delay - this has now been resolved and the files are available again.
